version: '3.8'

services:
  mydb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
  
  app:
    build: .
    depends_on:
      - mydb
    command: bash -c 'while !</dev/tcp/mydb/3306; do sleep 1; done; npm start'
    links:
      - mydb
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT